import ReduxProvider from "@/store/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar";
import MiniCart from "@/components/MiniCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "E Commerce Application",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <NavBar />
                    <MiniCart />
                    {children}
                </ReduxProvider>
            </body>
        </html>
    );
}
